//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Codigo { get; set; }
        public int IdTipoArea { get; set; }
        public string Descripcion { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual TipoArea TipoArea { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
