//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociado
    {
        public Asociado()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public int IdTipoAsociado { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string Celular { get; set; }
        public string CedulaIdentidad { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string DireccionOfi { get; set; }
        public string TelefonoOfi { get; set; }
        public string DireccionDom { get; set; }
        public string TelefonoDom { get; set; }
        public string Profesion { get; set; }
        public string Empresa { get; set; }
        public string CargoEmpresa { get; set; }
        public string PaisProc { get; set; }
        public string CiudadProc { get; set; }
        public string Email { get; set; }
        public bool Enmora { get; set; }
        public bool Eliminado { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual TipoAsociado TipoAsociado { get; set; }
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
