//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int Id { get; set; }
        public int IdAsociado { get; set; }
        public int IdParentesco { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string CedulaIdentidad { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual Asociado Asociado { get; set; }
        public virtual Parentesco Parentesco { get; set; }
    }
}
