//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoReserva
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public string Observacion { get; set; }
        public decimal Monto { get; set; }
        public bool Eliminado { get; set; }
        public int IdReserva { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
