//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolancoFinalEntities : DbContext
    {
        public PolancoFinalEntities()
            : base("name=PolancoFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alumno> Alumno { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Asociado> Asociado { get; set; }
        public DbSet<Beneficiario> Beneficiario { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<Deporte> Deporte { get; set; }
        public DbSet<PagoCurso> PagoCurso { get; set; }
        public DbSet<PagoReserva> PagoReserva { get; set; }
        public DbSet<Parentesco> Parentesco { get; set; }
        public DbSet<Profesor> Profesor { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<TipoArea> TipoArea { get; set; }
        public DbSet<TipoAsociado> TipoAsociado { get; set; }
    }
}
