//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int Id { get; set; }
        public int CodigoE { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Nombres { get; set; }
        public string CedulaIdentidad { get; set; }
        public string Telefono { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
