//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_Extraordinaria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.PagoReserva = new HashSet<PagoReserva>();
        }
    
        public int Codigo { get; set; }
        public int IdAsociado { get; set; }
        public int CodAsociado { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string CedulaIdentidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TelefonoRef { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<decimal> Garantia { get; set; }
        public int CodigoArea { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Pagada { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Asociado Asociado { get; set; }
        public virtual ICollection<PagoReserva> PagoReserva { get; set; }
    }
}
